### ISSUE TITLE
Provide regex pattern for EasyPost API keys

### ISSUE THREAD

**Issue by max-wittig** [EasyPost/easy-ui#1139]
Hi! We're using [gitleaks](https://github.com/gitleaks/gitleaks) internally to find secrets that developers might have accidentally leaked. Gitleaks uses this pattern to find `EasyPost` API keys: `\\bEZTK(?i)\[a-z0-9\]{54}`. See: https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml#L349

Sadly this pattern does not work for the two example keys that I've found in the wild: https://docs.gitguardian.com/secrets-detection/secrets-detection-engine/detectors/specifics/easypost_api_key#examples

![image](https://github.com/EasyPost/easy-ui/assets/6639323/e4a56cc0-72ae-443a-92ae-f7803d1ee297)

Would you mind to provide a corrected pattern or some example API keys, so that we can make the life of developers using `EasyPost` more secure? Thanks!

**Comment by nwithan8** [comment]
Hello @max-wittig , thanks for reaching out. We've gone ahead and forwarded your request internally to the proper team, and going to go ahead and close this issue here since it's not related to our UI elements.

I'm a bit confused about your request, however. It looks like the first line in the screenshot did match the provided regex pattern. The second line did not match because it starts with "EZAK" (the prefix for production API keys) rather than "EZTK" (the prefix for test keys).

**Comment by max-wittig** [comment]
@nwithan8 Thanks for the response! Yes I just created the issue in a random repo. I will contact the support email.

The main problem of the pattern is the amount of false-positives that we find.
